### ISSUE TITLE
Publish latest version on npm

### ISSUE THREAD

**Issue by AaronPlave** [jcsmorais/shortcut-buttons-flatpickr#37]
Would it be possible to publish the latest version of this library to NPM? I'm looking to make use of https://github.com/jcsmorais/shortcut-buttons-flatpickr/pull/31 but it's not part of the 0.3.1 NPM package. Thanks!

**Comment by hracik** [comment]
@jcsmorais 
any chance this can be done this year?

**Comment by jcsmorais** [comment]
Took a little longer than expected but just published 0.4.0 🎉

**Comment by AaronPlave** [comment]
Excellent, thank you!
