### ISSUE TITLE
Accessibility and Keyboard controls

### ISSUE THREAD

**Issue by plumpNation** [jcsmorais/shortcut-buttons-flatpickr#5]
First let me say, thanks for opening up your work for all of us, it's extremely generous.

https://codepen.io/the-plumpNation/pen/xaPrjP

I added another input to your codepen example (found here https://github.com/flatpickr/flatpickr/issues/576) so that the basic form keyboard controls (tabbing mainly) could be tested also.

Tabbing from one input to the next works as expected.

When I use the arrow keys, I begin interacting with the picker as expected, and if I now tab, the shortcut buttons focus correctly. Nice!

However, when I tab from the last shortcut button, I now no longer experience the same behaviour as when not using the plugin, which is to *tab back to the input that this datepicker belongs to.

I also wondered what would be the best way of alerting a screenreader to the fact that these shortcuts now exist.

Thanks again! If I find some time, I will take a look myself, if not, it's documented here if anyone else fancies a go.

**Comment by jcsmorais** [comment]
@plumpNation thanks for your issue report 👍 

I added https://github.com/jcsmorais/shortcut-buttons-flatpickr/commit/73624d6dfbcff6743dc2dd233dfa742be238fb57 to master that aims to solve what you described above regarding the shortcut buttons plugin making flatpickr's behavior a little different than the out-of-the-box behavior when the plugin is not being used and one tabs through the different visible elements.

Let me know if that works for you.
