### ISSUE TITLE
How to use in react

### ISSUE THREAD

**Issue by kenzouno1** [jcsmorais/shortcut-buttons-flatpickr#6]
I like this plugin but i can't import to my react project. i try import but always error `shortcutButtonsPlugin is not defined`

`import 'shortcut-buttons-flatpickr';`
`import { ShortcutButtonsPlugin } from 'shortcut-buttons-flatpickr';`
`import ShortcutButtonsPlugin from 'shortcut-buttons-flatpickr';`

**Comment by jcsmorais** [comment]
@kenzouno1 can you try the following?
```ts
import { ShortcutButtonsPlugin } from 'shortcut-buttons-flatpickr/dist/types/index.d';

// ...

flatpickr('#calendar', {
    // flatpickr options
    plugins: [
        ShortcutButtonsPlugin({
            // shortcut buttons plugin options
        }),
    ],
});
```
Let me know if it works, or in case it doesn't, which error messages you're getting.
