### ISSUE TITLE
IE problem

### ISSUE THREAD

**Issue by kplogo** [jcsmorais/shortcut-buttons-flatpickr#8]
You have typed "target": "es6" in tsconfig. it is a problem because it is not working on IE (IE does not support arrowed function:)

**Comment by jcsmorais** [comment]
@kplogo thanks for reporting this issue.

I did that 'cause on the projects where I'm using this plugin (the ones that triggered me to build it in the 1st place) have no requirements around IE support.

I agree it'd be a nice to have though and I had other requests in the recent past asking for IE support too.

Would you like to take a stab at it? I'd certainly welcome any contributions 😃
